# Generated by Django 4.0.6 on 2022-07-28 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_description', models.CharField(max_length=50, unique=True)),
                ('Installation_Date', models.DateTimeField()),
                ('Expiry_Date', models.DateTimeField()),
                ('Responsible_person', models.CharField(max_length=30)),
               # ('active', models.BooleanField()),
            ],
        ),
    ]
