# Generated by Django 4.0.6 on 2022-07-29 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_license_responsible_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='Responsible_person',
            field=models.CharField(choices=[('System Admin', 'System Admin'), ('Network Admin', 'Network Admin'), ('o', 'Other')], max_length=50),
        ),
    ]
