# Generated by Django 4.0.6 on 2022-08-14 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_license_responsible_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='license',
            name='Expiry_Date',
            field=models.DateField(),
        ),
    ]
